from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SiteEntry:
    label: str
    url: str
    aliases: tuple[str, ...] = ()


COMMON_TRANSCRIPT_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    (r"\bopen[- ]brand\b", "open brave"),
    (r"\bopen the raf\b", "open brave"),
    (r"\braf\b", "brave"),
    (r"\bchat gpt\b", "chatgpt"),
    (r"\bchat gpp\b", "chatgpt"),
    (r"\bchagibity\b", "chatgpt"),
    (r"\bchadgpt\b", "chatgpt"),
    (r"\bcharge equity\b", "chatgpt"),
    (r"\bopen hit\b", "open it"),
    (r"\bdiscard\b", "discord"),
    (r"\bthe brief\b", "brave"),
    (r"\bthe raise\b", "brave"),
    (r"\bplay-up\b", "play"),
    (r"\bduck duck go\b", "duckduckgo"),
    (r"\bgoogle clout\b", "google cloud"),
    (r"\blinked in\b", "linkedin"),
    (r"\bnotion so\b", "notion"),
    (r"\bprime vedio\b", "prime video"),
)


SITE_CATALOG: tuple[SiteEntry, ...] = (
    SiteEntry("Google", "https://google.com", ("google search",)),
    SiteEntry("ChatGPT", "https://chatgpt.com", ("openai chatgpt",)),
    SiteEntry("Perplexity", "https://perplexity.ai"),
    SiteEntry("Claude", "https://claude.ai"),
    SiteEntry("Gemini", "https://gemini.google.com", ("google gemini",)),
    SiteEntry("Bing", "https://bing.com"),
    SiteEntry("DuckDuckGo", "https://duckduckgo.com", ("duck duck go",)),
    SiteEntry("You.com", "https://you.com", ("you dot com",)),
    SiteEntry("Phind", "https://phind.com"),
    SiteEntry("Poe", "https://poe.com"),
    SiteEntry("Notion", "https://notion.so"),
    SiteEntry("Obsidian", "https://obsidian.md"),
    SiteEntry("Evernote", "https://evernote.com"),
    SiteEntry("Google Keep", "https://keep.google.com"),
    SiteEntry("Todoist", "https://todoist.com"),
    SiteEntry("Trello", "https://trello.com"),
    SiteEntry("Asana", "https://asana.com"),
    SiteEntry("ClickUp", "https://clickup.com"),
    SiteEntry("Microsoft OneNote", "https://onenote.com", ("onenote",)),
    SiteEntry("Workflowy", "https://workflowy.com"),
    SiteEntry("GitHub", "https://github.com"),
    SiteEntry("GitLab", "https://gitlab.com"),
    SiteEntry("Stack Overflow", "https://stackoverflow.com", ("stackoverflow",)),
    SiteEntry("Replit", "https://replit.com"),
    SiteEntry("CodePen", "https://codepen.io"),
    SiteEntry("LeetCode", "https://leetcode.com"),
    SiteEntry("HackerRank", "https://hackerrank.com"),
    SiteEntry("Dev.to", "https://dev.to", ("devto",)),
    SiteEntry("Hashnode", "https://hashnode.com"),
    SiteEntry("Vercel", "https://vercel.com"),
    SiteEntry("Netlify", "https://netlify.com"),
    SiteEntry("npm", "https://npmjs.com", ("npmjs",)),
    SiteEntry("MDN Web Docs", "https://developer.mozilla.org", ("mdn", "mozilla docs")),
    SiteEntry("Hugging Face", "https://huggingface.co", ("huggingface",)),
    SiteEntry("Kaggle", "https://kaggle.com"),
    SiteEntry("Coursera", "https://coursera.org"),
    SiteEntry("freeCodeCamp", "https://freecodecamp.org", ("free code camp",)),
    SiteEntry("W3Schools", "https://w3schools.com"),
    SiteEntry("GeeksforGeeks", "https://geeksforgeeks.org", ("geeks for geeks",)),
    SiteEntry("Roadmap.sh", "https://roadmap.sh", ("roadmap",)),
    SiteEntry("Instagram", "https://instagram.com"),
    SiteEntry("X", "https://x.com", ("twitter", "x.com")),
    SiteEntry("Reddit", "https://reddit.com"),
    SiteEntry("LinkedIn", "https://linkedin.com", ("linked in",)),
    SiteEntry("Facebook", "https://facebook.com"),
    SiteEntry("Snapchat", "https://snapchat.com"),
    SiteEntry("Pinterest", "https://pinterest.com"),
    SiteEntry("Threads", "https://threads.net"),
    SiteEntry("Discord", "https://discord.com"),
    SiteEntry("Telegram Web", "https://web.telegram.org", ("telegram",)),
    SiteEntry("WhatsApp Web", "https://web.whatsapp.com", ("whatsapp",)),
    SiteEntry("Mastodon", "https://mastodon.social"),
    SiteEntry("Quora", "https://quora.com"),
    SiteEntry("Medium", "https://medium.com"),
    SiteEntry("Tumblr", "https://tumblr.com"),
    SiteEntry("YouTube", "https://youtube.com"),
    SiteEntry("Netflix", "https://netflix.com"),
    SiteEntry("Prime Video", "https://primevideo.com", ("amazon prime video",)),
    SiteEntry("Disney+", "https://disneyplus.com", ("disney plus",)),
    SiteEntry("Crunchyroll", "https://crunchyroll.com"),
    SiteEntry("Twitch", "https://twitch.tv"),
    SiteEntry("Spotify", "https://spotify.com"),
    SiteEntry("SoundCloud", "https://soundcloud.com"),
    SiteEntry("JioSaavn", "https://jiosaavn.com", ("jio saavn",)),
    SiteEntry("Gaana", "https://gaana.com"),
    SiteEntry("IMDb", "https://imdb.com", ("imdb",)),
    SiteEntry("Rotten Tomatoes", "https://rottentomatoes.com"),
    SiteEntry("Letterboxd", "https://letterboxd.com"),
    SiteEntry("Genius Lyrics", "https://genius.com", ("genius",)),
    SiteEntry("VLC Web", "https://videolan.org", ("videolan", "vlc")),
    SiteEntry("Wikipedia", "https://wikipedia.org"),
    SiteEntry("Britannica", "https://britannica.com"),
    SiteEntry("Khan Academy", "https://khanacademy.org"),
    SiteEntry("edX", "https://edx.org"),
    SiteEntry("Udemy", "https://udemy.com"),
    SiteEntry("Skillshare", "https://skillshare.com"),
    SiteEntry("MIT OpenCourseWare", "https://ocw.mit.edu", ("mit ocw",)),
    SiteEntry("FutureLearn", "https://futurelearn.com"),
    SiteEntry("DeepLearning.AI", "https://deeplearning.ai", ("deep learning ai",)),
    SiteEntry("Brilliant", "https://brilliant.org"),
    SiteEntry("Codecademy", "https://codecademy.com"),
    SiteEntry("SoloLearn", "https://sololearn.com", ("solo learn",)),
    SiteEntry("TED", "https://ted.com"),
    SiteEntry("ResearchGate", "https://researchgate.net"),
    SiteEntry("Google Scholar", "https://scholar.google.com", ("scholar",)),
    SiteEntry("Canva", "https://canva.com"),
    SiteEntry("Figma", "https://figma.com"),
    SiteEntry("Dribbble", "https://dribbble.com"),
    SiteEntry("Behance", "https://behance.net"),
    SiteEntry("Adobe Express", "https://express.adobe.com"),
    SiteEntry("Pixlr", "https://pixlr.com"),
    SiteEntry("Photopea", "https://photopea.com"),
    SiteEntry("Unsplash", "https://unsplash.com"),
    SiteEntry("Pexels", "https://pexels.com"),
    SiteEntry("Freepik", "https://freepik.com"),
    SiteEntry("Remove.bg", "https://remove.bg", ("remove background",)),
    SiteEntry("Coolors", "https://coolors.co"),
    SiteEntry("Font Awesome", "https://fontawesome.com"),
    SiteEntry("Google Fonts", "https://fonts.google.com"),
    SiteEntry("Spline", "https://spline.design"),
    SiteEntry("TradingView", "https://tradingview.com", ("trading view",)),
    SiteEntry("Zerodha", "https://zerodha.com"),
    SiteEntry("Groww", "https://groww.in"),
    SiteEntry("CoinMarketCap", "https://coinmarketcap.com", ("coin market cap",)),
    SiteEntry("Yahoo Finance", "https://finance.yahoo.com"),
    SiteEntry("Moneycontrol", "https://moneycontrol.com"),
    SiteEntry("NSE India", "https://nseindia.com", ("nse",)),
    SiteEntry("Paytm", "https://paytm.com"),
    SiteEntry("PhonePe", "https://phonepe.com", ("phone pe",)),
    SiteEntry("Google Pay", "https://pay.google.com", ("gpay",)),
    SiteEntry("Razorpay", "https://razorpay.com"),
    SiteEntry("Stripe", "https://stripe.com"),
    SiteEntry("Wise", "https://wise.com"),
    SiteEntry("Binance", "https://binance.com"),
    SiteEntry("Coinbase", "https://coinbase.com"),
    SiteEntry("Amazon", "https://amazon.in", ("amazon india",)),
    SiteEntry("Flipkart", "https://flipkart.com"),
    SiteEntry("Myntra", "https://myntra.com"),
    SiteEntry("Ajio", "https://ajio.com"),
    SiteEntry("Meesho", "https://meesho.com"),
    SiteEntry("eBay", "https://ebay.com", ("ebay",)),
    SiteEntry("Alibaba", "https://alibaba.com"),
    SiteEntry("AliExpress", "https://aliexpress.com", ("ali express",)),
    SiteEntry("Etsy", "https://etsy.com"),
    SiteEntry("OLX", "https://olx.in"),
    SiteEntry("Croma", "https://croma.com"),
    SiteEntry("Reliance Digital", "https://reliancedigital.in"),
    SiteEntry("Tata Cliq", "https://tatacliq.com"),
    SiteEntry("Nykaa", "https://nykaa.com"),
    SiteEntry("Pepperfry", "https://pepperfry.com"),
    SiteEntry("Gmail", "https://gmail.com", ("google mail",)),
    SiteEntry("Outlook", "https://outlook.com"),
    SiteEntry("Proton Mail", "https://proton.me", ("protonmail",)),
    SiteEntry("Zoom", "https://zoom.us"),
    SiteEntry("Google Meet", "https://meet.google.com", ("meet",)),
    SiteEntry("Slack", "https://slack.com"),
    SiteEntry("Microsoft Teams", "https://teams.microsoft.com", ("teams",)),
    SiteEntry("Calendly", "https://calendly.com"),
    SiteEntry("Skype", "https://skype.com"),
    SiteEntry("Zoho Mail", "https://zoho.com/mail"),
    SiteEntry("Google Drive", "https://drive.google.com", ("drive",)),
    SiteEntry("Dropbox", "https://dropbox.com"),
    SiteEntry("OneDrive", "https://onedrive.live.com", ("one drive",)),
    SiteEntry("MEGA", "https://mega.nz"),
    SiteEntry("Box", "https://box.com"),
    SiteEntry("WeTransfer", "https://wetransfer.com", ("we transfer",)),
    SiteEntry("iCloud", "https://icloud.com", ("icloud",)),
    SiteEntry("Sync", "https://sync.com"),
    SiteEntry("MediaFire", "https://mediafire.com"),
    SiteEntry("pCloud", "https://pcloud.com"),
    SiteEntry("BBC", "https://bbc.com"),
    SiteEntry("Reuters", "https://reuters.com"),
    SiteEntry("The Verge", "https://theverge.com", ("verge",)),
    SiteEntry("TechCrunch", "https://techcrunch.com"),
    SiteEntry("Hacker News", "https://news.ycombinator.com", ("hn",)),
    SiteEntry("Ars Technica", "https://arstechnica.com"),
    SiteEntry("Wired", "https://wired.com"),
    SiteEntry("NDTV", "https://ndtv.com"),
    SiteEntry("Indian Express", "https://indianexpress.com"),
    SiteEntry("The Hindu", "https://thehindu.com"),
    SiteEntry("TinyWow", "https://tinywow.com", ("tiny wow",)),
    SiteEntry("ILovePDF", "https://ilovepdf.com", ("i love pdf",)),
    SiteEntry("Smallpdf", "https://smallpdf.com"),
    SiteEntry("Speedtest", "https://speedtest.net"),
    SiteEntry("Fast.com", "https://fast.com", ("fast dot com",)),
    SiteEntry("Temp Mail", "https://temp-mail.org", ("temporary mail",)),
    SiteEntry("10 Minute Mail", "https://10minutemail.com", ("ten minute mail",)),
    SiteEntry("DownDetector", "https://downdetector.com", ("down detector",)),
    SiteEntry("VirusTotal", "https://virustotal.com", ("virus total",)),
    SiteEntry("Pastebin", "https://pastebin.com"),
    SiteEntry("JSON Formatter", "https://jsonformatter.org"),
    SiteEntry("Regex101", "https://regex101.com", ("regex 101",)),
    SiteEntry("Excalidraw", "https://excalidraw.com"),
    SiteEntry("Draw.io", "https://draw.io", ("draw io",)),
    SiteEntry("Convertio", "https://convertio.co"),
    SiteEntry("Internshala", "https://internshala.com"),
    SiteEntry("Naukri", "https://naukri.com"),
    SiteEntry("Indeed", "https://indeed.com"),
    SiteEntry("Wellfound", "https://wellfound.com"),
    SiteEntry("LinkedIn Jobs", "https://linkedin.com/jobs"),
    SiteEntry("Upwork", "https://upwork.com"),
    SiteEntry("Fiverr", "https://fiverr.com"),
    SiteEntry("Freelancer", "https://freelancer.com"),
    SiteEntry("Turing", "https://turing.com"),
    SiteEntry("Remote OK", "https://remoteok.com"),
    SiteEntry("ElevenLabs", "https://elevenlabs.io", ("eleven labs",)),
    SiteEntry("Runway", "https://runwayml.com", ("runway ml",)),
    SiteEntry("Leonardo AI", "https://leonardo.ai", ("leonardo",)),
    SiteEntry("Midjourney", "https://midjourney.com"),
    SiteEntry("Suno", "https://suno.com"),
    SiteEntry("HeyGen", "https://heygen.com", ("hey gen",)),
    SiteEntry("Gamma", "https://gamma.app"),
    SiteEntry("Bolt", "https://bolt.new", ("bolt new",)),
    SiteEntry("Lovable", "https://lovable.dev"),
    SiteEntry("Cursor", "https://cursor.com"),
    SiteEntry("Windsurf", "https://windsurf.com"),
    SiteEntry("Firecrawl", "https://firecrawl.dev"),
    SiteEntry("n8n", "https://n8n.io"),
    SiteEntry("Zapier", "https://zapier.com"),
    SiteEntry("Make", "https://make.com"),
    SiteEntry("Product Hunt", "https://producthunt.com"),
    SiteEntry("AlternativeTo", "https://alternativeto.net", ("alternative to",)),
    SiteEntry("Archive.org", "https://archive.org", ("archive org",)),
    SiteEntry("Wayback Machine", "https://web.archive.org", ("wayback",)),
    SiteEntry("EarthCam", "https://earthcam.com", ("earth cam",)),
    SiteEntry("Radio Garden", "https://radio.garden"),
    SiteEntry("WindowSwap", "https://window-swap.com", ("window swap",)),
    SiteEntry("HackerOne", "https://hackerone.com", ("hacker one",)),
    SiteEntry("Exploding Topics", "https://explodingtopics.com"),
    SiteEntry("Nomad List", "https://nomadlist.com"),
    SiteEntry("Google Cloud", "https://cloud.google.com", ("gcp", "googlecloud")),
)
